### ISSUE TITLE
Deprecation warning in Ember 3.0

### ISSUE THREAD

**Issue by nelnico** [EmberSherpa/ember-element-resize-detector#7]
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: site-xxx-> ember-light-table -> ember-scrollable -> ember-element-resize-detector -> ember-cli-babel

**Comment by Gaurav0** [comment]
This should be fixed in your apps by v0.2.0
