### ISSUE TITLE
Failure in Ember 3.2

### ISSUE THREAD

**Issue by jrjohnson** [EmberSherpa/ember-element-resize-detector#9]
I'm getting the following error when attempting to upgrade to Ember 3.2 which appears to come from 
https://github.com/EmberSherpa/ember-element-resize-detector/blob/master/addon/components/resize-detector.js#L31

`Uncaught Error: Assertion Failed: Attempted to call .sendAction() with the action 'on-resize' on the destroyed object '<ilios@component:resize-detector::ember199658>'.`

**Comment by john-griffin** [comment]
@jrjohnson does this fix things for you? https://github.com/ember-animation/liquid-fire/issues/616#issuecomment-402844873

**Comment by jrjohnson** [comment]
Yes, @john-griffin thanks! Updating my `@ember/test-helpers` and converting failing tests to the new qunit API did the trick!
